### PR TITLE
The monitor json route return all jobs regardless of the current user

### PR DESCRIPTION
**Pull request by dbyrns**
This new feature will probably never be merged into birdhouse/master so keep it in the pavics-0.1 branch.

### CODE REVIEW

**Comment by tomLandry** [comment]
Is that a security hazard?

**Comment by dbyrns** [comment]
Kind of. This is why I will not merge it into the master branch. For Pavics, phoenix will be used as a backend so we don't have to worry about it. For now it helps Felix, for later we will see if the user filtering should be reactivated on the backend or handled in the frontend.

**Comment by tomLandry** [comment]
Please put a ticket in the backlog to keep a track on this, so we won't merge or we will enhance the feature. Also, not 100% sure but I think that is what Twitcher is for.

**Comment by dbyrns** [comment]
Are you sure that we should open a ticket for all commits targeting the pavics branch rather than master? I mean, features from pavics should be evaluated properly before trying to merge them into master.

**Comment by tomLandry** [comment]
If we have a process to be sure not to mess up by mistake, you're right. Depends on what we look for when we merge. Here, we know in advance that this is risky code.

**Comment by dbyrns** [comment]
I agree with that.

**Pull request merged**
